### ISSUE TITLE
请教一下大佬，calculateZA中的参数uid代表的是什么

### ISSUE THREAD

**Issue by svenman1012** [emmansun/sm2js#6]
[calculateZA](https://github.com/emmansun/sm2js/blob/fcd43676f7958e9ed1acf93d6bbf658e97b8b9e3/src/sm2.js#L243)

**Comment by emmansun** [comment]
就是用户标识符啊，不过大都用默认值，也就是不传这个参数就可以。

**Comment by svenman1012** [comment]
感谢大佬，我再研究一下

**Comment by emmansun** [comment]
SM2签名规范里面有：
![image](https://user-images.githubusercontent.com/7235232/224880040-319493de-810e-46f3-b9ff-beaec9d035c5.png)
